# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OutlineVpn < Formula
  desc "outline-vpn helps you easily and quickly provision EC2 with terraform and consume vpn service on your mobile or computer via outline application."
  homepage "https://github.com/ghdwlsgur/outline-vpn"
  version "1.0.20"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ghdwlsgur/outline-vpn/releases/download/v1.0.20/outline-vpn_1.0.20_Darwin_arm64.tar.gz"
      sha256 "a04f1a304b471d77a35bded0263ea158b6410022413efb15c4320437a54d24b8"

      def install
        bin.install "outline-vpn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/outline-vpn/releases/download/v1.0.20/outline-vpn_1.0.20_Darwin_x86_64.tar.gz"
      sha256 "a8dc41bdfe84ab0a018ca98515ef8b31f111cd5ea3ff011d1128865b31b80a81"

      def install
        bin.install "outline-vpn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/outline-vpn/releases/download/v1.0.20/outline-vpn_1.0.20_Linux_arm64.tar.gz"
      sha256 "ea3a774fec4224582446bf2d189933aad118a6a0fe070d1be99711dee3c0c6cd"

      def install
        bin.install "outline-vpn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/outline-vpn/releases/download/v1.0.20/outline-vpn_1.0.20_Linux_x86_64.tar.gz"
      sha256 "bcb4bcb35f74394dadf64df540c4c8c12a650a44d598d223b949d087327adcb8"

      def install
        bin.install "outline-vpn"
      end
    end
  end
end
